---
controller_credentials:
- name: AWS EC2 Credential
  description: API Credentials for AWS
  organization: "{{ my_organization }}"
  credential_type: Amazon Web Services
  inputs:
    username: "{{ aws_access_key }}"
    password: "{{ aws_secret_key }}"

- name: Machine Credential for Instances
  description: SSH Key Credential for Linux VMs
  organization: "{{ my_organization }}"
  credential_type: Machine
  inputs:
    username: "{{ ssh_username }}"
    ssh_key_data: "{{ ssh_priv_key }}"
    become_method: sudo

- name: ServiceNow Dev
  description: ServiceNow ITSM Credential for Dev 
  organization: "{{ my_organization }}"
  credential_type: ServiceNow ITSM Credential
  inputs:
    instance: "{{ snow_instance }}"
    password: "{{ snow_password }}"
    username: "{{ snow_username }}"
    
