---
eda_credentials:
  - name: Controller Credential
    description: AAP credentials
    credential_type: 'Red Hat Ansible Automation Platform'
    organization: "{{ my_organization }}"
    inputs:
      host: "{{ aap_hostname }}/api/controller/"
      password: "{{ aap_password }}"
      username: admin
      verify_ssl: false

  - name: Event Stream Token Credential
    description: Credential for a token event stream
    credential_type: Token Event Stream
    organization: "{{ my_organization }}"
    inputs:
      auth_type: token
      http_header_key: Authorization
      token: "{{ eda_event_stream_token }}"