---
gateway_settings:
  gateway_access_token_expiration: 86400
  gateway_basic_auth_enabled: true
  SESSION_COOKIE_AGE: 86400
  custom_login_info: |-
    WARNING: SECURED IT ENVIRONMENT
    This system is strictly for authorized use only. 
    All user activity on this network is monitored, recorded, and subject to audit. 
    Any unauthorized access or attempted breach is a violation of security policies. 
    Violators will be fully investigated and subject to legal prosecution and 
    eporting to law enforcement authorities.
