---
- name: Apply Configuration as Code to AAP 2.7
  hosts: localhost
  gather_facts: false
  connection: local
  become: false

  vars:
    ansible_async_dir: '/tmp/.ansible_async'
  
  pre_tasks:
    - name: Load declarative AAP configurations
      ansible.builtin.include_vars:
        dir: ../config
        extensions:
          - 'yml'
          - 'yaml'
  tasks:    
  - name: Apply AAP Configuration
    ansible.builtin.include_role:
      name: infra.aap_configuration.dispatch
